---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] All Tests"
run-name: "[Tests] All Tests"

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
      - release-*

  # Trigger workflow when enqueued to a merge group
  # (must be under 'on')
  merge_group: {}

# Only run at most 1 workflow concurrently per pushed commit
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  SUPASS: ${{ secrets.SUPASS }}
  BUILD_TYPE: DAILY

permissions:
  contents: read

jobs:
  run_basic_acceptance_tests:
    runs-on: [all]
    name: "Basic Acceptance Tests"
    timeout-minutes: 35
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Basic Acceptance Tests
        run: |
          make clean-all
          make run_basic_acceptance_tests

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_functional_tests:
    runs-on: [all]
    name: "Functional Tests"
    timeout-minutes: 55
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Functional Tests
        run: |
          make clean-all
          make run_functional_tests

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_non_functional_tests:
    runs-on: [all]
    name: "Non-Functional Tests"
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Non-Functional Tests
        run: |
          make clean-all
          make run_non_functional_tests

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_metric_tests:
    runs-on: [all]
    name: "Metric Tests"
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Metric Tests
        run: |
          make clean-all
          make run_metric_tests

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_ui_tests:
    runs-on: [all]
    name: "UI Tests"
    timeout-minutes: 45
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run UI Tests
        run: |
          make clean-all
          make run_ui_tests

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_unit_tests:
    runs-on: [all]
    name: "Unit Tests"
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Unit Tests
        run: |
          make clean-all
          make run_unit_tests

      - name: Upload Logs and Reports
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup
